// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE4OaIUO5S0ZC9sAfRcv0WKdRZjIOcylA',
    appId: '1:58649514855:web:150cf36e422c5d477715c2',
    messagingSenderId: '58649514855',
    projectId: 'agrivsla',
    authDomain: 'agrivsla.firebaseapp.com',
    storageBucket: 'agrivsla.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh_ik2ZKXYxC43iW34uLlpYsWugRUGqRM',
    appId: '1:58649514855:android:7e1b2a906acd37487715c2',
    messagingSenderId: '58649514855',
    projectId: 'agrivsla',
    storageBucket: 'agrivsla.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKzrnwG7OuoFTengi4JPeHfLHYV1T-yVM',
    appId: '1:58649514855:ios:40a5f1513d2b21907715c2',
    messagingSenderId: '58649514855',
    projectId: 'agrivsla',
    storageBucket: 'agrivsla.firebasestorage.app',
    iosBundleId: 'com.example.ratek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKzrnwG7OuoFTengi4JPeHfLHYV1T-yVM',
    appId: '1:58649514855:ios:40a5f1513d2b21907715c2',
    messagingSenderId: '58649514855',
    projectId: 'agrivsla',
    storageBucket: 'agrivsla.firebasestorage.app',
    iosBundleId: 'com.example.ratek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE4OaIUO5S0ZC9sAfRcv0WKdRZjIOcylA',
    appId: '1:58649514855:web:450c6245c337e19a7715c2',
    messagingSenderId: '58649514855',
    projectId: 'agrivsla',
    authDomain: 'agrivsla.firebaseapp.com',
    storageBucket: 'agrivsla.firebasestorage.app',
  );

}