// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxsWTdZdM8oHF5W9x_dmj79Li2QJ1nZK8',
    appId: '1:891859102098:web:640a085cbd86d7d57d394b',
    messagingSenderId: '891859102098',
    projectId: 'agripoa-b54d1',
    authDomain: 'agripoa-b54d1.firebaseapp.com',
    storageBucket: 'agripoa-b54d1.appspot.com',
    measurementId: 'G-N98BC85DV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5dG2Ds0lUSbq1QEuTDRMXrzmCksqlyP0',
    appId: '1:891859102098:android:0f8ce931eafa95c87d394b',
    messagingSenderId: '891859102098',
    projectId: 'agripoa-b54d1',
    storageBucket: 'agripoa-b54d1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzwyISsx4w5J4mT_Cw1FMui65jcMe63s0',
    appId: '1:891859102098:ios:7f214ec82ecebee17d394b',
    messagingSenderId: '891859102098',
    projectId: 'agripoa-b54d1',
    storageBucket: 'agripoa-b54d1.appspot.com',
    iosBundleId: 'com.example.ratek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzwyISsx4w5J4mT_Cw1FMui65jcMe63s0',
    appId: '1:891859102098:ios:7f214ec82ecebee17d394b',
    messagingSenderId: '891859102098',
    projectId: 'agripoa-b54d1',
    storageBucket: 'agripoa-b54d1.appspot.com',
    iosBundleId: 'com.example.ratek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxsWTdZdM8oHF5W9x_dmj79Li2QJ1nZK8',
    appId: '1:891859102098:web:6f7e45e4f8ca25e17d394b',
    messagingSenderId: '891859102098',
    projectId: 'agripoa-b54d1',
    authDomain: 'agripoa-b54d1.firebaseapp.com',
    storageBucket: 'agripoa-b54d1.appspot.com',
    measurementId: 'G-G1HWWT0F7K',
  );
}
